### ISSUE TITLE
[Install] Error: invalid option: --without-x86_64 when install musl package

### ISSUE THREAD

**Issue by feliciss** [rooch-network/omo#62]
Command:

```bash
brew install FiloSottile/musl-cross/musl-cross --without-x86_64 --with-mips
```

Mentioned:

[docs/dev/apple_silicon.md](https://github.com/rooch-network/omo/blob/main/docs/dev/apple_silicon.md)

https://github.com/rooch-network/omo#installing-musl-toolchains

May be fixed by:

https://github.com/FiloSottile/homebrew-musl-cross/issues/17

**Comment by lerencao** [comment]
@templexxx please have a look

**Comment by templexxx** [comment]
@feliciss It appears to be an issue with the 'brew' prohibiting the 'install option.' Have you tried a complete installation?

**Comment by feliciss** [comment]
> @feliciss It appears to be an issue with the 'brew' prohibiting the 'install option.' Have you tried a complete installation?

idk, I just followed the tutorials on a fresh machine and it failed.

**Comment by templexxx** [comment]
> > @feliciss It appears to be an issue with the 'brew' prohibiting the 'install option.' Have you tried a complete installation?
> 
> idk, I just followed the tutorials on a fresh machine and it failed.

how about this:

```
brew install FiloSottile/musl-cross/musl-cross
```

I tried to uninstall musl-cross then use:

```
brew install FiloSottile/musl-cross/musl-cross --without-x86_64 --with-mips
```

everything is okay, weird

**Comment by feliciss** [comment]
> > > @feliciss It appears to be an issue with the 'brew' prohibiting the 'install option.' Have you tried a complete installation?
> > 
> > 
> > idk, I just followed the tutorials on a fresh machine and it failed.
> 
> how about this:
> 
> ```
> brew install FiloSottile/musl-cross/musl-cross
> ```
> 
> I tried to uninstall musl-cross then use:
> 
> ```
> brew install FiloSottile/musl-cross/musl-cross --without-x86_64 --with-mips
> ```
> 
> everything is okay, weird

That's exactly what means in the issue: https://github.com/FiloSottile/homebrew-musl-cross/issues/17

One should install without flags, uninstall it, and reinstall with flags again on a fresh machine. 

So, I would like to change the README to include this problem.

**Comment by feliciss** [comment]
> I met another issue: cannot find symbol when install mips-linux-musl

Sorry I didn't happen to have installed `mips-linux-musl-cross`, and I had successfully reinstalled with `musl-cross`.

**Comment by templexxx** [comment]
> > I met another issue: cannot find symbol when install mips-linux-musl
> 
> Sorry I didn't happen to have installed `mips-linux-musl-cross`, and I had successfully reinstalled with `musl-cross`.

it doesn't make sense. I did that days ago. But today failed caused by  symbol(s) not found for architecture arm64 on my macOS 13.4 when uninstall and reinstall. emmm

**Comment by feliciss** [comment]
> 

Can you show me the steps you executed the above command?

I just executed the same command:

```bash
/opt/homebrew/opt/make/bin/gmake install TARGET=mips-linux-musl
```

But it showed that

```bash
gmake: *** No rule to make target 'install'.  Stop.
```

**Comment by templexxx** [comment]
> > 
> 
> Can you show me the steps you executed the above command?
> 
> I just executed the same command:
> 
> ```shell
> /opt/homebrew/opt/make/bin/gmake install TARGET=mips-linux-musl
> ```
> 
> But it showed that
> 
> ```shell
> gmake: *** No rule to make target 'install'.  Stop.
> ```



> > 
> 
> Can you show me the steps you executed the above command?
> 
> I just executed the same command:
> 
> ```shell
> /opt/homebrew/opt/make/bin/gmake install TARGET=mips-linux-musl
> ```
> 
> But it showed that
> 
> ```shell
> gmake: *** No rule to make target 'install'.  Stop.
> ```

this output is from the last part of:

```
brew install FiloSottile/musl-cross/musl-cross --without-x86_64 --with-mips
```

just after:

```
brew uninstall FiloSottile/musl-cross/musl-cross
```

**Comment by feliciss** [comment]
> > Can you show me the steps you executed the above command?
> > I just executed the same command:
> > ```shell
> > /opt/homebrew/opt/make/bin/gmake install TARGET=mips-linux-musl
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But it showed that
> > ```shell
> > gmake: *** No rule to make target 'install'.  Stop.
> > ```
> 
> this output is from the last part of:
> 
> ```
> brew install FiloSottile/musl-cross/musl-cross --without-x86_64 --with-mips
> ```
> 
> just after:
> 
> ```
> brew uninstall FiloSottile/musl-cross/musl-cross
> ```

Ah I got it. I have the same error after dangling too long:

```bash
==> /opt/homebrew/opt/make/bin/gmake install TARGET=mips-linux-musl
Last 15 lines from /Users/system/Library/Logs/Homebrew/musl-cross/01.gmake:
      ___cxx_global_var_init in gencondmd.o
  "_mips_isa_rev", referenced from:
      ___cxx_global_var_init in gencondmd.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[3]: *** [Makefile:2865: build/gencondmd] Error 1
gmake[3]: *** Waiting for unfinished jobs....
19 warnings generated.
rm gcc.pod
gmake[3]: Leaving directory '/private/tmp/musl-cross-20230615-70626-9mdw3m/musl-cross-make-0.9.9/build/local/mips-linux-musl/obj_gcc/gcc'
gmake[2]: *** [Makefile:4360: all-gcc] Error 2
gmake[2]: Leaving directory '/private/tmp/musl-cross-20230615-70626-9mdw3m/musl-cross-make-0.9.9/build/local/mips-linux-musl/obj_gcc'
gmake[1]: *** [Makefile:222: obj_gcc/gcc/.lc_built] Error 2
gmake[1]: Leaving directory '/private/tmp/musl-cross-20230615-70626-9mdw3m/musl-cross-make-0.9.9/build/local/mips-linux-musl'
gmake: *** [Makefile:183: install] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/filosottile/homebrew-musl-cross/issues
```

I reported it here. Sorry for misconfusion.
